### ISSUE TITLE
[Question] Openssl version used for build your mac client

### ISSUE THREAD

**Issue by xataz** [nextcloud/client_theming#73] opened 2017-02-10 10:45 UTC
Hello,

Sorry for my bad english ^^.
I'm install nextcloud on my server, with letsencrypt ssl (ECDSA 384bits), and I sync with my computers.
I use restrictive ciphers (ECDHE-ECDSA with CHACHA or AES) with tlsv1.2 protocole.
On windows/linux/IOS/android, no problem with client, but on macOS, i have an error (connection closed).

I suspect the version of openssl used to build.
In order to locate the problem, can you tell me which version of openssl you are using for build your client ?

Thanks and regards.

**Comment by Wonderfall** [comment] 2017-02-15 17:07
Duplicate of https://github.com/nextcloud/client_theming/issues/13 :)

**Closed as completed by Wonderfall** 2017-02-15 17:07 UTC
Labels: question
