### ISSUE TITLE
Make NextCloud Icon Bigger

### ISSUE THREAD

**Issue by jean-io** [nextcloud/client_theming#43] opened 2016-11-04 16:20 UTC
Hi,

Could you make NextCloud icon bigger please? I find it a little too small.

![exemple](https://cloud.githubusercontent.com/assets/4070933/20013305/ea1626c8-a2b2-11e6-9e6c-21e795db0127.png)

I am not sure I am posting this issue in the right place, but tanks anyway 😄 

**EDIT**

This is the right place.

**Comment by zbraniecki** [comment] 2016-11-08 20:58
FYI, works great on Gnome 3.

**Comment by XueSheng-GIT** [comment] 2017-02-11 19:20
I'm using Ubuntu 16.04 with nextcloud sync client.
Imho the icon is too small. It's hard to see if syncing is active or finished. The default color (blue) isn't really visible on the dark ground (at least it's possible to change to monochrome).

Hope the icon gets a rework.

**Comment by LukasReschke** [comment] 2017-02-14 08:39
cc @jancborchardt

**Comment by jancborchardt** [comment] 2017-02-14 09:30
Yes, I also thought about this. The problem is that the logo is very wide.

I would actually just go for the simple round shape without incorporating the logo. Then it's properly visible and also simple. cc @nextcloud/designers @karlitschek what do you think?

**Comment by karlitschek** [comment] 2017-02-14 09:35
hmm. there are pro and cons.  But I guess it is ok to no longer use the logo but a simple round checkbox instead. Would be OK with me.

**Comment by skjnldsv** [comment] 2017-02-14 09:46
Ok here too :)

**Comment by eppfel** [comment] 2017-02-14 10:29
Not against it. Just a reminder, that it still has to be distinctive:
<img width="244" alt="bildschirmfoto 2017-02-14 um 11 27 39" src="https://cloud.githubusercontent.com/assets/1899308/22925346/9e8bebfc-f2a8-11e6-84fc-6a042e691000.png">

A lot of circles already... 😁

**Comment by elioqoshi** [comment] 2017-02-14 11:44
Does the icon need to be fitted in a square? If yes, then it makes sense to use a circle (if it's well distinguished)

**Comment by JSoko** [comment] 2017-02-14 12:08
Just my 5 cents:

Leave the icon an use a bright round background
Just quick and dirty:
actual:
![ncicon1](https://cloud.githubusercontent.com/assets/5583290/22928397/93fc1d7a-f2b6-11e6-8504-58eb55da7c6e.jpg)
bright background:
![ncicon2](https://cloud.githubusercontent.com/assets/5583290/22928398/93fc3c60-f2b6-11e6-8dba-75218610a0f7.png)

**Comment by raimund-schluessler** [comment] 2017-02-14 13:16
With a round background it reminds me of a pokeball :smile: 
![pokeball](https://cloud.githubusercontent.com/assets/2496460/22930260/ad99a884-f2bf-11e6-8937-00601cd7a507.PNG)

**Comment by Bugsbane** [comment] 2017-02-18 12:43
Gotta sync'em all!

**Comment by tribut** [comment] 2017-03-22 11:43
Even worse with the monochrome icons. No way to tell which state the client is in on a hi-dpi display without a magnifying glass :mag: 

![screenshot from 2017-03-22 12-45-04](https://cloud.githubusercontent.com/assets/719105/24196260/681a3eea-0efd-11e7-81d8-b3b1a6f9acc2.png)

**Comment by enoch85** [comment] 2017-06-05 15:18
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by MariusBluem** [comment] 2017-06-05 16:20
Not solved.

**Comment by jean-io** [comment] 2017-06-06 09:52
Not solved. Thank @MariusBluem

This is clearly a NextCloud icon and not an OwnCloud icon. As mentioned by @jancborchardt (icon too wide) this is a NC issue.

**Comment by enoch85** [comment] 2017-06-06 11:07
Trying to clean up some issues here. Didn't read the actual issue. Thanks for pointing it out.

**Comment by jean-io** [comment] 2017-06-06 12:24
@enoch85 no problem :smiley:

**Comment by jancborchardt** [comment] 2017-08-15 14:30
Pull request at https://github.com/nextcloud/client_theming/pull/200, please review :)

**Comment by jean-io** [comment] 2017-08-17 08:13
thank @jancborchardt 

It looks great!!! 👍  🎉

**Comment by jancborchardt** [comment] 2017-08-24 15:08
Fixed with the new icons at https://github.com/nextcloud/client_theming/pull/200 – will be in the next release I guess, @rullzer? :)

**Comment by rullzer** [comment] 2017-08-24 15:10
Should be yeah

**Closed as completed by rullzer** 2017-08-24 15:10 UTC

**Comment by jean-io** [comment] 2017-08-25 20:47
Thank, great work 👍  🎆  😄
