### ISSUE TITLE
Updated icons are not ok

### ISSUE THREAD

**Issue by mihaiile** [nextcloud/client_theming#201] opened 2017-08-24 09:36 UTC
### Actual behaviour
I applaud the time spent in developing this application and I know is easy to just complain, but unfortunately the new icons to me are still not ok.
1. just a check mark does not identify which application is that
2. the icon is HUGE! in fact is so big that the top and bottom has 0px in Ubuntu top bar, is just huge, something you would expect to see in a UI that is optimised for your grandparents.
While I do understand in the past was too small, I would say too big is also not that good... A compromise has to be taken to have a good design and a pleasing application to use.

This is how it is showing up, to me it is completely non professional and not appealing:
![image](https://user-images.githubusercontent.com/3273985/29659215-cfbe05ce-88bd-11e7-986c-40a754bea1fa.png)

### Expected behaviour
To address the 2 points above I would suggest to have a compromise where first the icons have to be scaled down a bit.
Second, why don't take the idea of what the green icon I have in above screen shot does and use a variation of that with what we had before, the original logo image where we could use a cropped version of before and after circles but in a horizontal line instead of 45 degrees the green icon has them. Yes it will make the icon smaller but I guess it will still be acceptable?
 
### Environment data
Ubuntu 17.04

Nextcloud app version:
Version 2.3.2

**Comment by golderweb** [comment] 2017-08-24 13:09
I also feel very uncomfortable with this change. Those really huge icons are very disturbing as they do not match the normal look and feel of the ubuntu tray.
![Way to massive Icon in Ubuntu Systray](https://user-images.githubusercontent.com/3439392/29667804-15aaf7a2-88de-11e7-8ff5-8ba51dfd36f4.png)

Every time I wander over the screen with my eyes this massive icon catches my attention. Just realising that it is worth nothing cause everything is in sync.

**Comment by elpraga** [comment] 2017-08-24 17:56
I do agree. The new icons are **way too** big, and they don't provide any visual clue about the app they refer to. 

And the icons in the account tab seem to be a clear mistake. 
![screenshot from 2017-08-24 19-54-23](https://user-images.githubusercontent.com/13814570/29680847-290e15e0-8906-11e7-8224-63f6d8e49cf0.png)

(I don't know if they actually are a mistake, but they certainly look like one)

**Comment by rullzer** [comment] 2017-08-25 08:08
@jancborchardt please have a look

**Comment by jancborchardt** [comment] 2017-08-25 16:26
@rullzer that’s why I ask if it’s possible to preview how it looks in the tray. ;)

A first step would be to just add 1 or 2px whitespace on each side. @rullzer is there an automatic way we can do that or test it?

**Comment by ghost** [comment] 2017-08-27 12:34
There does need to be a visual cue as to what application this checkmark is from. Just a generic checmark doesn't tell me it's Nextcloud, so yeah I don't quite understand the change here. Why did you change it to this?

**Comment by jancborchardt** [comment] 2017-08-27 19:59
Here’s the issues and discussions which led to the change: https://github.com/nextcloud/client_theming/issues/43 & https://github.com/nextcloud/client_theming/issues/196

I’m working on a fix, further comments are not helping.

**Comment by jds2726** [comment] 2017-10-04 00:37
I agree that the new icons are too large (at least on osx), although i do prefer the style over the older over-complicated ones. 

On a more constructive note, the monochrome icons should be a gray rather than full black. They contrast too much, especially with the natural icon colors on osx are gray. That color btw is (R:30 G:63 B:76). Its also often used in windows notification tray apps.

<img width="369" alt="screen shot 2017-10-03 at 8 36 33 pm" src="https://user-images.githubusercontent.com/24447220/31155245-9670590c-a87a-11e7-865f-5ba0ec00b209.png">

@jancborchardt I'm willing to help change the icon colors over if you'd like, I'd just need to familiarize myself with the project first. Thanks for your efforts!

**Comment by jancborchardt** [comment] 2017-10-04 13:08
@jds2726 thanks a lot, especially for the color note! :) Is it the same for when you invert the colors? If so, could you let me know the RGB color as well?

**Comment by jds2726** [comment] 2017-10-04 14:21
@jancborchardt I assume your refering to dark mode in os x, which (kinda) inverts the colors in the status bar. In dark mode the color for the menubar icons is full white R:255 G:255 B:255. Note that dark mode is still in development so this might change in newer OS releases. Here's a screenshot for further reference.

<img width="385" alt="screen shot 2017-10-04 at 10 16 52 am" src="https://user-images.githubusercontent.com/24447220/31180866-bf3cf296-a8ed-11e7-900c-ad9e766a72fb.png">

In case you were referring to invert colors in accessibility settings for some reason here's the color 
 for the icons when that's enabled R:23 G:48 B:60

**Comment by jds2726** [comment] 2017-10-04 14:56
@jancborchardt Also, I'm a huge fan of minimalist design but the circles might be a little too ambiguous, as other threads have pointed out. A cloud outline icon might look better - i personally prefer icons like this:

<img width="538" alt="screen shot 2017-10-04 at 10 52 40 am" src="https://user-images.githubusercontent.com/24447220/31182592-47e8693c-a8f2-11e7-8a5f-1daf56bc74a0.png">

You could then put the state icons inside of the cloud (All Synced, Syncing, & Pause - Like icons). Just a personal preference and my two cents.

**Comment by alexanderdd** [comment] 2017-11-15 21:12
on xubuntu 17.04, xfce4.12, the icon gets cut off at the top and at the bottom for panel heights lower than 26 pixels (expected behavior: icon resizes just like the other ones for panel heigts lower than 26)
![grafik](https://user-images.githubusercontent.com/28591861/32860492-0beadfd8-ca52-11e7-87ee-b232110af979.png)

**Comment by krukai** [comment] 2017-11-29 13:51
I also dislike this change. The old icons were perfect in my eyes: simple, small, informative, not intrusive at all, and it was clear what application they belonged to. Branding the tray icons makes sense. Now they are overly generic and, thanks to their size and color scheme, intrusive.

I would love an option to select a preferred icon set.
![lxqt](https://user-images.githubusercontent.com/22506122/33377911-648321b6-d513-11e7-8ecd-180f301c9c6d.png)
This is how my tray currently looks with LxQt. Right now, it might as well be the icon of a virus scanner I downloaded along with the Ask! toolbar.

**Comment by wiertz** [comment] 2017-12-07 19:09
I agree, the new icon is terri... eh... "not OK".

**Comment by zoc** [comment] 2017-12-17 11:56
Just updated my Nextcloud client today, then reverted to 2.3.2 only because of that ugly "thing" at the top-right corner of the screen (I'm on a Mac with black menubar).

Overlay icons in the finder are good, but that one... no, sorry, no...

**Comment by MegaV0lt** [comment] 2018-01-09 07:53
Why not use teh nextcloud-logo with statusovelayicons?

**Comment by jancborchardt** [comment] 2018-01-09 09:22
@MegaV0lt that's one plan, yes.

**Comment by MegaV0lt** [comment] 2018-01-09 09:56
Good. Any Plan how they could look?
 I made two quick and dirty samples what they cold look like:
![auswahl_20180109_10 54 52](https://user-images.githubusercontent.com/2804301/34715080-b1c09516-f52b-11e7-98f8-c804f6829e45.png)
![auswahl_20180109_10 54 30](https://user-images.githubusercontent.com/2804301/34715084-b4fc8a5a-f52b-11e7-9384-a7dc76b02ce5.png)

**Comment by jancborchardt** [comment] 2018-01-09 10:03
@MegaV0lt it needs to work from 16*16px on, and as monochrome. You can see more at https://github.com/nextcloud/client_theming/pull/200

So the way to do it would be to take only the Nextcloud icon full-size, and put the new/current status icons a bit smaller (smaller than the big circle) overlaying on the bottom right (maybe with a bit of margin to the bottom right so it looks nice visually).

You are very welcome to experiment here or help out. :)

**Comment by MegaV0lt** [comment] 2018-01-09 10:47
Ok, just bring the old style icons back. They are exist in different resolutions:
![auswahl_20180109_11 45 26](https://user-images.githubusercontent.com/2804301/34717257-beb50e44-f532-11e7-93eb-78e68b983f34.png)

The old ones on the left side are much better

 PS. Overview of the (bad) change:
![](https://user-images.githubusercontent.com/925062/29070347-41f6e74a-7c3f-11e7-9359-5d6085deb452.png)

**Comment by MegaV0lt** [comment] 2018-01-09 10:55
I think it should be very easy to convert the old style icons to the new ones including mono and inversed style

**Comment by jancborchardt** [comment] 2018-01-09 14:11
@MegaV0lt just changing it back to the old ones is not a solution, no. We changed it specifically because there was user feedback (and it was quite obvious too) that the old icons were very small and the status is not visible enough.

So, to put it as clear as possible for anyone who wants to help here:

- Take only the Nextcloud icon full-size, basically as before, but in default identity white (or black for the mono-black version)
- Put the new/current status icons a bit smaller (smaller than the big circle) overlaying on the bottom right (maybe with a bit of margin to the bottom right so it looks nice visually). For the monochrome version, they need to have a slight cutoff from the Nextcloud logo so they don’t stick together.
- It needs to work from 16*16px on, and as monochrome. You can see more at #200

**Further comments about disliking the current icons do not help and will be deleted to reduce the noise. Use +1 on the main issue to express your agreement if you have nothing to add except that. Thanks**

**Comment by MegaV0lt** [comment] 2018-01-09 15:18
The problem was only affecting the non colored icons. why not only use the new icons there. the old ones are pretty good when colored

**Comment by schokonsti** [comment] 2018-01-13 22:09
I made a suggestion in the original thread: [new state icons](https://github.com/nextcloud/client_theming/issues/196#issuecomment-357467673), maybe it could be of use...

**Comment by jancborchardt** [comment] 2018-01-30 12:50
@MegaV0lt because that does not take into account people who have problems distinguishing colors. The forms need to be distinguishable.

**Comment by jancborchardt** [comment] 2018-01-30 12:57
Closing in favor of #196 as there are more proposals there. :)

**Closed as completed by jancborchardt** 2018-01-30 12:57 UTC
