### ISSUE TITLE
A nextcloud icon is missing in desktop notifications.

### ISSUE THREAD

**Issue by elpraga** [nextcloud/client_theming#169] opened 2017-06-09 08:27 UTC
Expected behavior:
correct icon appears in desktop notifications
Actual behavior:
Missing icon symbol appears in desktop notifications.

Hot Fix:
`cp /usr/share/icons/hicolor/64x64/apps/Nextcloud.png /usr/share/pixmaps/owncloud.png`

Please note, that the __Nextcloud__ client still expect an __ownlcloud__ icon. The hotfix doesn't work when `nextcloud.png` is used.

Ubuntu 17.04
Nextcloud client 2.3.1

**Comment by juliusknorr** [comment] 2017-06-09 16:25
Closing as this is a duplicate of https://github.com/nextcloud/client_theming/issues/86 

A fix has already been merged upstream for the next version. :wink:

**Closed as completed by juliusknorr** 2017-06-09 16:25 UTC

**Comment by elpraga** [comment] 2017-06-10 13:54
@juliushaertl are you sure that the issue #86 involves the correct copy of the icon in `/usr/share/pixmaps/` ?

**Comment by Igric** [comment] 2017-06-12 14:12
Цц

9 июня 2017 г. 11:27 AM пользователь "elpraga" <notifications@github.com>
написал:

**Comment by elpraga** [comment] 2017-06-12 20:25
Я не понимаю @Igric

**Comment by juliusknorr** [comment] 2017-06-13 10:45
@elpraga There is no copy needed, the client will now look for a 'Nextcloud.png' icon when creating notifications.

**Comment by elpraga** [comment] 2017-06-13 17:14
Great! I'll check it out when it rolls out!
