### ISSUE TITLE
Pls add Linux binary or/and deb, rpm installers for Nextcloud client

### ISSUE THREAD

**Issue by AngryPenguinPL** [nextcloud/client_theming#32] opened 2016-10-05 19:30 UTC
Hi, nextcloud team.

I want install NextCloud client on my Linux but in download page I see only source for Linux. Why not binary or installers?
OwnCloud have rpm and deb files for download and you only sources?

Pls release binary or installers for Linux distros. We need it.

Regards.

**Comment by nathanael-h** [comment] 2016-10-08 10:28
Hi, I share xpris'opinion, please release binaries. I do not know how to compile sources. I did not understand what's written in the readme file. 
Have a nice week-end, thank's for NextCloud !

**Comment by powerriegel** [comment] 2016-10-10 05:50
Same opinion. I'm a cumputer scientist but it did not compile on my Ubuntu. Packages missing (sqlite3) but after installing them, same error occurred (sqlite not found). It's no good idea to force customers without IT background to compile something. 

Until there is a binary, I will use the owncloud client which works without problems.

**Comment by nursoda** [comment] 2016-10-12 18:41
+1

**Comment by Corvan** [comment] 2016-10-13 13:16
+1

**Comment by nathanael-h** [comment] 2016-10-14 16:05
Hello @rullzer could you help us by providing binaries for GNU/Linux OS ?

**Comment by compuguy** [comment] 2016-10-16 00:21
I know this won't solve the issue with a lack of a repo, but there is an appimage proposal in #29

**Comment by rullzer** [comment] 2016-10-17 06:20
The issue with packages is that they break. We have seen it before and we will see it again. Some distro will change a tiny thing and it will all fall apart. And since I myself don't use any of the deb/rpm packages testing this properly is a real pain.

We are looking into how to solve this in a suistainable way (just dumping a staticly compiled binary somewhere in an rpm is not going to fly for me).

**Comment by nursoda** [comment] 2016-10-17 07:28
While I fully understand your point, there is a significant user base on ubuntu based distros. Part of them hardly know how to install using the distros installer. They should be able to click-and-install. The way owncloud did it (through SuSEs build-environment) works well for me - why not use this until any better idea is there?

**Comment by Corvan** [comment] 2016-10-17 07:51
another big point is resolving dependencies. For simple users it is not convenient at all to run cmake as long as ist does not print out missing dependencies anymore, so that they finally can run make and make install.

**Comment by danielholm** [comment] 2016-10-17 16:52
+1

**Comment by posliedov** [comment] 2016-10-20 11:27
+1

**Comment by nathanael-h** [comment] 2016-10-20 12:39
Hello, I understand that it is not so easy for you to provide binaries for all the distros, because of the differences. But when I wanted to install nextcloud client on my ubuntu installation it did not work easily. So how could we both expect non tech people to use open source OS, open source cloud and compile the client for this cloud system on this OS ? 
For me the best should be to have a packet in official distro repo for ubuntu(s), arch, debian, fedora. And with the prefered app manager click and install nextcloud client :)

**Comment by powerriegel** [comment] 2016-10-20 12:50
Hello everybody. Ubuntu Gnome 16.04 brings **native** Owncloud support (Calendar, Contacts, WebDAV). Works very well with NextCloud. But of course, I don't know when NextCloud will differ from Owncloud to much and clients won't work longer. 
@nath: Packets in the OS packet managers are often outdated. No good idea for a quick developing open-source tool.

**Comment by Corvan** [comment] 2016-10-20 13:09
@powerriegel  That is of course a very cool thing, I will definetaly check that out; but I was thinking about moving from Gnome.
The packages are often outdated because there is no package maintainer for them :-(

**Comment by jisse44** [comment] 2016-10-21 07:26
Hi, for Fedora you can use tpokorra packages: https://copr.fedorainfracloud.org/coprs/tpokorra/nextcloud/

**Comment by rullzer** [comment] 2016-10-21 08:00
@jisse44 awesome!

**Comment by probonopd** [comment] 2016-10-22 11:39
So, what is wrong with the [AppImage](http://appimage.org/)?

**Comment by happyreacer** [comment] 2016-10-22 21:27
look for archlinux (and for example manjaro)
[https://aur.archlinux.org/packages/nextcloud-client/](url)

**Comment by morph027** [comment] 2016-11-01 10:50
See https://github.com/nextcloud/client_theming/issues/25#issuecomment-254232998

**Comment by morph027** [comment] 2016-11-01 13:43
https://gitlab.com/packaging/nextcloud-client/

No clue of opensuse build service...but should be easy to migrate to travis ci.

**Comment by raoel** [comment] 2016-11-06 11:31
@morph027: that's a good start. Debian Jessie does not seem to have version "GLIBCXX_3.4.21" (I checked and goes up to 3.4.20). I tried following the commands on your gitlab-page and I get stuck here:

```
$ cmake -DCMAKE_INSTALL_PREFIX=/usr -D OEM_THEME_DIR=`pwd`/../nextcloudtheme ../client
CMake Error: The source directory "/tmp/client_theming/client" does not appear to contain CMakeLists.txt.
```

Please note, I've never used cmake in my life. I am a lousy frontend-developer :-) The googles did not give an apparent solution.

As my server is Nextcloud version 9.1, which does not seem to work with the available Owncloud-client, I am without backups right now, which is a scary thought... I work with multiple OS's on my machine and I have been copying to-and-forth a lot lately. 
I am sure this is all temporary, but currently it is annoying enough that I have to learn how to compile from source with cmake without [breaking Debian](https://wiki.debian.org/DontBreakDebian).

**Comment by morph027** [comment] 2016-11-06 12:19
Hm, looks like also kio-dev and extra-cmake-modulesare available in strech only.

Did you fetched all repos and submodules?

**Comment by raoel** [comment] 2016-11-16 20:36
Ah, I thought git clone would fetch everything, never used `git submodule` before.

Building it was not easy, had to install all kinds of dependencies I never heard of, ended up with some warnings.
After make && make install I had an error 
`version `GLIBCXX_3.4.21' not found`
Latest version of Debian Jessie provides up to 3.4.20.
Retrieved a more recent package for libstdc6++, unpackaged libstdc++.so.6.0.22 and changed the link in the filesystem, as I don't want to break debian.

Now nextcloud starts with an error:
`QT_MESSAGE_PATTERN: Unknown placeholder %{time MM-dd hh:mm:ss:zzz}`
I think this is due to one of the warnings. I have no clue how to fix them.

I tried nextcloudcmd but it stops at:

```
nextcloudcmd: symbol lookup error: /usr/lib/x86_64-linux-gnu/libnextcloudsync.so.0: undefined symbol: _ZN9QMetaType22registerNormalizedTypeERK10QByteArrayPFvPvEPFS3_S3_PKvEi6QFlagsINS_8TypeFlagEEPK11QMetaObject
```

No, I would not say "just build it yourself" is a solution.

Output of cmake:

```
cmake -D OEM_THEME_DIR=`pwd`/../nextcloudtheme ../client
-- Build of crashreporter disabled.
-- GIT_SHA1 eaeed08544d1d7f4031d28a8e1bd9dd5e08a60fd
-- Could NOT find INOTIFY (missing:  INOTIFY_LIBRARY_DIR) 
-- Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE) 
-- Could NOT find PdfLatex (missing:  PDFLATEX_EXECUTABLE) 
-- Found SQLite3: /usr/lib/x86_64-linux-gnu/libsqlite3.so (Required is at least version "3.8.0") 
-- Found SQLite3: /usr/lib/x86_64-linux-gnu/libsqlite3.so;/usr/lib/x86_64-linux-gnu/libsqlite3.so (Required is at least version "3.8.0") 
-- Found Qt5 core, checking for further dependencies...
-- Using Qt 5!
-- If possible compile me with Qt 5.4 or higher.
CMake Warning at shell_integration/CMakeLists.txt:11 (find_package):
  By not providing "FindKF5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "KF5", but
  CMake did not find one.

  Could not find a package configuration file provided by "KF5" (requested
  version 5.16) with any of the following names:

    KF5Config.cmake
    kf5-config.cmake

  Add the installation prefix of "KF5" to CMAKE_PREFIX_PATH or set "KF5_DIR"
  to a directory containing one of the above files.  If "KF5" provides a
  separate development package or SDK, be sure it has been installed.


Dolphin plugin disabled: KDE Frameworks 5.16 not found
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/client_theming/build-linux
```

I installed:
- qtkeychain-dev
- qt5keychain-dev
- cmake
- doxygen
- libssl-dev
- libsqlite3-dev
- qt5-default
- libqt5webkit5-dev
- qttools5-dev-tools

**Comment by jowolf** [comment] 2016-12-13 18:39
+1
Having both iOS and Android apps, but no desktop binaries for Ubuntu (and Mint, etc derivatives), which is the leading Desktop Linux by far, seems backwards.

**Comment by jacmoe** [comment] 2016-12-14 07:39
@rullzer Installing this client on my wife's machine is not really going to fly with me (or her) either.
I am a developer and I already have a fully fledged development environment on my machine, but I'd rather not have to install all of that on her laptop -> CMake, Qt5, .. that is a lot of baggage, isn't it?

I think an appimage script could mean that we can all have our cake and eat it too?
It could just be automated, so that you don't have to worry about it too much.
Not all Linux users are power users. My wife is not. :)

This is not a complaint - just trying to put things into perspective.

**Comment by probonopd** [comment] 2016-12-14 19:12
> I think an appimage script could mean that we can all have our cake and eat it too?
It could just be automated, so that you don't have to worry about it too much.

That's exactly what https://github.com/nextcloud/client_theming/pull/29 would do if it was merged: It would automatically build and upload an AppImage for each git push.

**Comment by jacmoe** [comment] 2016-12-18 06:22
I am now using the Owncloud client, and it seems to work fine.
However, I expect that to change as the two projects diverges.

**Comment by bentalexanderhaase** [comment] 2017-01-10 14:02
Any news about updates for the client / binary packages for Linux distros? It has been three months, are you working on a completely new Nextcloud client behind the curtains maybe?

**Comment by probonopd** [comment] 2017-01-13 18:20
An AppImage is now being built for each commit and stored to temporary storage for 14 days on transfer.sh. The download URL can be seen in the [Travis CI build log](https://travis-ci.org/nextcloud/client_theming/).

**Comment by bentalexanderhaase** [comment] 2017-01-13 20:32
@probonopd Shouldn't this be in the `README.md` somewhere as dozens of people are looking for this, yet no one except for you has brought up the CI? :O

[EDIT]: "build|passing" is the CI :man_facepalming: well I have been here a dozen times without noticing / clicking it. Bad me...

**Comment by probonopd** [comment] 2017-01-14 08:58
@ET-Bent we only have it since yesterday :-)

Eventually the AppImage could be linked here, what do you think?

![](https://lh3.googleusercontent.com/H0Cf0F-5FJZ21IHbGZMfnxx6iarglCfFlStZjQ-yNqmkyGpqiqV9YfE18MN48pzrr3J3CBTO3DWQbA=w717-h544-no)

**Comment by bentalexanderhaase** [comment] 2017-01-15 09:19
Haha well :relieved: 

Good idea to link it there @probonopd :+1:

**Comment by probonopd** [comment] 2017-01-15 12:57
@rullzer?

**Comment by AngryPenguinPL** [comment] 2017-01-15 19:07
I get this reply on twitter:

"
> included by openSUSE, Fedora. Debian/Ubuntu wip, linked on our install. We don't built packages, distro's do ;-)

"
https://twitter.com/Nextclouders/status/820705760107700228

So I think, app in third party repository is all what we can get from Nextcloud devs...

**Comment by jacmoe** [comment] 2017-01-15 19:13
@AngryPenguinPL If you care to follow the discussion, this is **not** the same thing :)

Edit:
It is actually a way for NextCloud to *avoid* having anything to do with packages and distros.

**Comment by rullzer** [comment] 2017-01-16 08:08
Tell me what to put where and I'll kick @jospoortvliet to put it there :wink:

**Comment by probonopd** [comment] 2017-01-16 20:59
Thanks @rullzer and @jospoortvliet I have opened its own issue for it, https://github.com/nextcloud/client_theming/issues/61

**Comment by rugk** [comment] 2017-03-19 17:08
Actually Travis seems [to have](https://travis-ci.org/nextcloud/client_theming/jobs/210959749) validation failures and thus cannot create a release. Also the links such to AppImages such as https://github.com/nextcloud/client_theming/releases/download/continuous/Nextcloud_desktop_sync_client_-gitdf8f32c-glibc2.14-x86_64.AppImage return 404 errors.

**Comment by rugk** [comment] 2017-03-19 17:08
The latest one I could get is https://transfer.sh/Oz2xp/nextcloud-desktop-sync-client-git6125460-glibc2.14-x86-64.appimage.

**Comment by probonopd** [comment] 2017-03-19 18:02
@rugk somehow the [uploadtool](https://github.com/probonopd/uploadtool) seems to have issues deleting the "continous" tag, and hence can't create a new one with the same name and upload the latest AppImage there. Most likely a bug in [uploadtool](https://github.com/probonopd/uploadtool). Any help appreciated. 

```
TRAVIS_COMMIT != tag_sha, hence deleting continuous...
Delete the release...
delete_url: https://api.github.com/repos/nextcloud/client_theming/releases/5719874
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
```

**Comment by enoch85** [comment] 2017-06-05 15:18
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by probonopd** [comment] 2017-06-05 16:00
Update: It's being worked on,
https://rullzer.com/nextcloud-desktop-client-appimage.html 👍

**Comment by enoch85** [comment] 2017-06-05 16:26
@probonopd Does this PR solve this issue? https://github.com/nextcloud/client_theming/pull/162

**Comment by enoch85** [comment] 2017-06-05 16:28
Btw, deb installers exist: https://github.com/nextcloud/client_theming#installing-on-debian

**Comment by probonopd** [comment] 2017-06-05 16:29
Well, the issue is solved once https://nextcloud.com/install/#install-clients provides something for Linux that we can download and run, not just source.

![screenshot_20170605_182841](https://cloud.githubusercontent.com/assets/2480569/26793072/e6f8175a-4a1c-11e7-915e-973da8371743.png)

**Comment by enoch85** [comment] 2017-06-05 16:32
@probonopd Well, snaps are available and works on any Linux system. I tested them myself. Problem is that we need someone to add them to the store (or something like that @3v1n0 knows what I mean) but no one have done it yet. Ping @oparoz or @rullzer on that one.

**Comment by rugk** [comment] 2017-06-13 18:49
Any plans for flatpaks?

**Comment by bentalexanderhaase** [comment] 2017-06-14 05:41
@rugk +1, man that'd be great. With some update about two months ago I felt like timetraveling with a DeLorean right back to the 90s.

**Comment by jospoortvliet** [comment] 2017-06-19 08:50
Our installation page links to https://help.nextcloud.com/t/linux-packages-status/10216 where you can find packages, provided by distributions. We won't create packages ourselves, it's been discussed to death.

(yes, we will end up doing app images, most likely, and there's a Snap)

**Closed as completed by jospoortvliet** 2017-06-19 08:50 UTC
