### ISSUE TITLE
Gnome Shell notifications still show ownCloud messages instead of Nextcloud

### ISSUE THREAD

**Issue by elpraga** [nextcloud/client_theming#134] opened 2017-05-02 23:13 UTC
I have the Nextcloud client installed, Nextcloud server running, yet, when the screen is locked, it tells me that I have messages from ownCloud. I guess some strings were left without translating.

**Comment by hanzei** [comment] 2017-05-11 07:50
Duplicate of #86
See owncloud/client#5677 for the fix

**Closed as completed by hanzei** 2017-05-11 07:50 UTC
