### ISSUE TITLE
Gnome notification shows OC icon

### ISSUE THREAD

**Issue by LennartRoeder** [nextcloud/client_theming#193] opened 2017-08-01 15:39 UTC
Hi,
the gnome notifications still show the ownCloud icon.

**Comment by juliusknorr** [comment] 2017-08-03 05:49
duplicate of #86

**Closed as completed by juliusknorr** 2017-08-03 05:49 UTC

**Comment by LennartRoeder** [comment] 2017-08-03 05:57
@juliushaertl I do not see what my ticket has to do with the lock screen. My gnome lockscreen does not have notifications of any kind. 
I am logged in and the notifications on the top of the screen shows the OC logo, like in the screenshot.
![screenshot from 2017-08-03 07-59-58](https://user-images.githubusercontent.com/1903874/28908081-c9adbf1e-7821-11e7-99bf-30c685fca47e.png)

**Comment by juliusknorr** [comment] 2017-08-03 06:12
@thinking-aloud The lockscreen issue was just about the shown notifications by the nextcloud client. The values were hardcoded and have been changed to use the Nextcloud icon and name provided by the client theme with https://github.com/owncloud/client/pull/5677 and https://github.com/nextcloud/client_theming/issues/170. 

So this should be fixed in the next release, I guess.

**Comment by LennartRoeder** [comment] 2017-08-03 06:13
Thank you
