### ISSUE TITLE
macOS client unable to connect to server

### ISSUE THREAD

**Issue by gellenburg** [nextcloud/client_theming#24] opened 2016-09-11 17:51 UTC
### Steps to reproduce
1. Launch NextCloud Mac Client 2.2.3 (build 4)
2. Enter server information (https://files.ellenburg.net/)
3. Click Next.

Receive pop-up "Unable to connect to secure server address"
![screenshot_191](https://cloud.githubusercontent.com/assets/7026750/18419329/3adc1fd4-7826-11e6-9359-0be5c3d71699.png)
### Expected behaviour

macOS client to be able to connect.
### Actual behaviour

macOS client is unable to connect.

**Note - the OwnCloud Client, version 2.2.3 (build 3601) connects just fine!**
![screenshot_192](https://cloud.githubusercontent.com/assets/7026750/18419332/442208f6-7826-11e6-880a-97a807a498ce.png)
### Server configuration

**Operating system**: Debian 8

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 10.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:** ?????
<details>
<summary>

Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

</details>

**List of activated apps:** Files, Gallery, Notes, Documents
<details>
<summary>

App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** N/A
#### LDAP configuration (delete this part if not used)

<details>
<summary>

LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

</details>
### Client configuration

**Browser:** Chrome, Firefox, and Safari

**Operating system:** macOS 10.12
#### Web server error log

<details>
<summary>

Web server error log</summary>

```
Insert your webserver log here
```

</details>
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
Insert your Nextcloud log here
```

</details>
#### Browser log

<details>
<summary>

Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by tflidd** [comment] 2016-09-13 20:07
You use TLSv1.2 only, there is already a report:
https://github.com/nextcloud/client_theming/issues/22

**Comment by rullzer** [comment] 2016-10-17 06:27
Duplicate of #13 indeed.

**Closed as completed by rullzer** 2016-10-17 06:27 UTC
Labels: duplicate
